#
# Copyright 2010-2012 Ettus Research LLC
#

##################################################
# CUSTOM Sources
##################################################
#CUSTOM_SRCS =$(abspath $(addprefix $(BASE_DIR)/../custom/, \
		custom_dsp_rx.v \
		/FFT_sq_m_sources/FFT_Sq_mag.v \
		/FFT_sq_m_sources/FFD.v \
		/FFT_sq_m_sources/data_synchronizer.v \
		/FFT_sq_m_sources/FFT/FFT.v \
	   	/FFT_sq_m_sources/FFT/control_unit_fft.v \
		/FFT_sq_m_sources/FFT/CU_fft_controller.v \
		/FFT_sq_m_sources/FFT/CU_ram_wr_controller.v \
	    	/FFT_sq_m_sources/FFT/datapath_fft_controller.v \
		/FFT_sq_m_sources/FFT/datapath_ram_wr_controller.v \
		/FFT_sq_m_sources/FFT/fft_controller.v \
		/FFT_sq_m_sources/FFT/ram_wr_controller.v \
		/FFT_sq_m_sources/FFT/tff_sync_reset.v \
		/FFT_sq_m_sources/Square_Mag/square_mag.v))
