#
# Copyright 2010 Ettus Research LLC
#


##################################################
# Coregen Sources
##################################################
COREGEN_SRCS = $(abspath $(addprefix $(BASE_DIR)/../coregen/, \
fifo_xlnx_2Kx36_2clk.v \
fifo_xlnx_2Kx36_2clk.xco \
fifo_xlnx_512x36_2clk.v \
fifo_xlnx_512x36_2clk.xco \
fifo_xlnx_64x36_2clk.v \
fifo_xlnx_64x36_2clk.xco \
fifo_xlnx_16x19_2clk.v \
fifo_xlnx_16x19_2clk.xco \
fifo_xlnx_16x40_2clk.v \
fifo_xlnx_16x40_2clk.xco \
fifo_xlnx_32x36_2clk.v \
fifo_xlnx_32x36_2clk.xco \
fifo_xlnx_512x36_2clk_36to18.v \
fifo_xlnx_512x36_2clk_36to18.xco \
fifo_xlnx_512x36_2clk_18to36.v \
fifo_xlnx_512x36_2clk_18to36.xco \
fifo_xlnx_512x36_2clk_prog_full.v \
fifo_xlnx_512x36_2clk_prog_full.xco \
/ed_adaptive_threshold_cores/FFT_cores/counter_mod_16.v \
/ed_adaptive_threshold_cores/FFT_cores/counter_mod_16.xco \
/ed_adaptive_threshold_cores/FFT_cores/counter_mod_10.v \
/ed_adaptive_threshold_cores/FFT_cores/counter_mod_10.xco \
/ed_adaptive_threshold_cores/FFT_cores/RAM_SP.v \
/ed_adaptive_threshold_cores/FFT_cores/RAM_SP.xco \
/ed_adaptive_threshold_cores/FFT_cores/fifo_generator_v6_2.v \
/ed_adaptive_threshold_cores/FFT_cores/fifo_generator_v6_2.xco \
/ed_adaptive_threshold_cores/FFT_cores/xfft_v7_1_ip_core.v \
/ed_adaptive_threshold_cores/FFT_cores/xfft_v7_1_ip_core.xco \
/ed_adaptive_threshold_cores/SQ_M_cores/dsp48_mul.v \
/ed_adaptive_threshold_cores/SQ_M_cores/dsp48_mul.xco \
/ed_adaptive_threshold_cores/SQ_M_cores/add.v \
/ed_adaptive_threshold_cores/SQ_M_cores/add.xco \
/ed_adaptive_threshold_cores/D_factor/av_accumulator.v \
/ed_adaptive_threshold_cores/D_factor/av_accumulator.xco \
/ed_adaptive_threshold_cores/ED_cores/acc_sub.v \
/ed_adaptive_threshold_cores/ED_cores/acc_sub.xco \
/ed_adaptive_threshold_cores/ED_cores/fifo_s1024.v \
/ed_adaptive_threshold_cores/ED_cores/fifo_s1024.xco))
