#
# Copyright 2010-2012 Ettus Research LLC
#

##################################################
# CUSTOM Sources
##################################################
CUSTOM_SRCS =$(abspath $(addprefix $(BASE_DIR)/../custom/, \
		custom_dsp_rx.v \
		/ED_sources_v2/ED_USRP.v \
		/ED_sources_v2/FFD.v \
		/ED_sources_v2/data_synchronizer.v \
		/ED_sources_v2/FFT/FFT.v \
	   	/ED_sources_v2/FFT/control_unit_fft.v \
		/ED_sources_v2/FFT/CU_fft_controller.v \
		/ED_sources_v2/FFT/CU_ram_wr_controller.v \
	    	/ED_sources_v2/FFT/datapath_fft_controller.v \
		/ED_sources_v2/FFT/datapath_ram_wr_controller.v \
		/ED_sources_v2/FFT/fft_controller.v \
		/ED_sources_v2/FFT/ram_wr_controller.v \
		/ED_sources_v2/FFT/tff_sync_reset.v \
		/ED_sources_v2/Square_Mag/square_mag.v \
		/ED_sources_v2/Energy_Detection/control_unit_detection.v \
		/ED_sources_v2/Energy_Detection/control_unit_ed.v\
		/ED_sources_v2/Energy_Detection/control_unit_packing.v\
		/ED_sources_v2/Energy_Detection/datapath_unit_ed.v\
		/ED_sources_v2/Energy_Detection/energy_detection_module.v\
		/ED_sources_v2/Energy_Detection/FFD_en.v))
