#
# Copyright 2010-2012 Ettus Research LLC
#
##################################################
# CUSTOM Sources
##################################################
#for ipcore use the same of the previous architecture
CUSTOM_SRCS =$(abspath $(addprefix $(BASE_DIR)/../custom/, \
		custom_dsp_rx.v \
		/ED_advanced_sources_v3/ED_USRP.v \
		/ED_advanced_sources_v3/FFD.v \
		/ED_advanced_sources_v3/data_synchronizer.v \
		/ED_advanced_sources_v3/FFT/FFT.v \
	   	/ED_advanced_sources_v3/FFT/control_unit_fft.v \
		/ED_advanced_sources_v3/FFT/CU_fft_controller.v \
		/ED_advanced_sources_v3/FFT/CU_ram_wr_controller.v \
	    	/ED_advanced_sources_v3/FFT/datapath_fft_controller.v \
		/ED_advanced_sources_v3/FFT/datapath_ram_wr_controller.v \
		/ED_advanced_sources_v3/FFT/fft_controller.v \
		/ED_advanced_sources_v3/FFT/ram_wr_controller.v \
		/ED_advanced_sources_v3/FFT/tff_sync_reset.v \
		/ED_advanced_sources_v3/Square_Mag/square_mag.v \
		/ED_advanced_sources_v3/DC_Elimination/dc_elimination.v \
		/ED_advanced_sources_v3/DC_Elimination/register_32b.v \
		/ED_advanced_sources_v3/D_Factor/d_factor_unit.v \
		/ED_advanced_sources_v3/D_Factor/maximum_unit.v \
		/ED_advanced_sources_v3/D_Factor/priority_encoder_32to6.v \
		/ED_advanced_sources_v3/D_Factor/shift_reg.v \
		/ED_advanced_sources_v3/Energy_Detection/control_unit_detection.v \
		/ED_advanced_sources_v3/Energy_Detection/control_unit_ed.v\
		/ED_advanced_sources_v3/Energy_Detection/control_unit_packing.v\
		/ED_advanced_sources_v3/Energy_Detection/datapath_unit_ed.v\
		/ED_advanced_sources_v3/Energy_Detection/energy_detection_module.v\
		/ED_advanced_sources_v3/Energy_Detection/FFD_en.v))

